-- AlterEnum
ALTER TYPE "Role" RENAME TO "Role_old";
CREATE TYPE "Role" AS ENUM ('CORE_ADMIN', 'TECHNICAL_LEAD', 'OPERATIONS_LEAD', 'RESEARCH_LEAD', 'OPERATIONS_PROGRAM_MANAGER', 'TECHNICAL_INTERN', 'OPERATIONS_INTERN', 'RESEARCH_INTERN', 'OBSERVER_TEAM_LEAD', 'COLLABORATOR_LEAD', 'ORENDA_MEMBER', 'PAST_EMPLOYEE');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role" USING (
  CASE "role"::text
    WHEN 'INTERN' THEN 'TECHNICAL_INTERN'::"Role"
    WHEN 'ADMIN' THEN 'CORE_ADMIN'::"Role"
    ELSE "role"::text::"Role"
  END
);
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'TECHNICAL_INTERN';
DROP TYPE "Role_old";
